name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run ruff linting
      run: uv run ruff check src/
    
    - name: Run ruff formatting check
      run: uv run ruff format --check src/
    
    - name: Run type checking
      run: uv run python -m py_compile src/isa_mcp_server/*.py
    
    - name: Run unit tests
      run: uv run python -m pytest tests/unit/ -v
    
    - name: Run integration tests
      run: uv run python -m pytest tests/integration/ -v
    
    - name: Test server import
      run: uv run python -c "from src.isa_mcp_server.server import mcp; print('Server imported successfully')"
    
    - name: Test ARM importer import
      run: uv run python -c "from src.isa_mcp_server.importers.arm_importer import ARMImporter; print('ARM importer imported successfully')"
    
    - name: Test ARM metadata parser import
      run: uv run python -c "from src.isa_mcp_server.arm_metadata_parser import ARMMetadataParser; print('ARM metadata parser imported successfully')"

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build package
      run: uv build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/